<?php

namespace ICanBoogie;

/**
 * @var $exception \Exception
 * @var $css array
 * @var $site \Icybee\Modules\Sites\Site
 * @var $code int
 * @var $class string
 * @var $reported bool
 * @var $formatted_exception string
 */

?><!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Icybee &ndash; Exception: <?= escape(shorten(strip_tags($exception->getMessage()), 32, 1)) ?></title>
<?php foreach($css as $url): ?>
<link href="<?= $url ?>" type="text/css" rel="stylesheet" />
<?php endforeach ?>
</head>

<body class="exception">

<div id="quick">←&nbsp;<a href="<?= $site ? $site->url : '/' ?>"><?= $site ? escape($site->title) : 'Home' ?></a></div>

<div class="actionbar clearfix">
	<div class="pull-xs-left">
		<div class="actionbar-title"><h1>Icybee <small><?= $code . ' ' . $class ?></small></h1></div>
	</div>
</div>

<div id="contents-wrapper">
	<div class="alert alert-danger"><pre><code><?= $formatted_exception ?></code></pre></div>
</div>

<footer><a href="http://www.icybee.org/" target="_blank">Icybee</a></footer>

</body>
</html>
